language: python
sudo: false
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
install:
- pip install --upgrade tox-travis -r requirements_build.txt
script:
- tox
deploy:
  skip_cleanup: true
  provider: script
  script: python scripts/release.py $TRAVIS_TAG
  on:
    branch: master
    tags: true
    condition: $TRAVIS_PYTHON_VERSION = "2.7"
notifications:
  on_success: always
  on_failure: always
  email: false
  slack:
    secure: OoSLX3FfX6P4apOgY1D9elSLj6/EwjS6GPdWbQxewairVbdrU07lDcYLX5GupoNGSgt9lUKI+K8C4BhDRGYFO0f044n7PodLLNA31reuOiQ1TknE492id0z45U1dhtiUzs6S1uIN6ZR8S072bh6TghjgrRsC6ijcjptMPzR8zACrEDOBL9AeS4ceG/09F16dXCwv0przzS78rzm4C2zyoF3Dci2YBhl0g42ifR00uhbmMb6OW6gWJ6KtQ4yFXznFLWH6/rEr0/OyaAFtuO8dvUIyKHvtchAHIHbUHdEGK6am6YQIqULx7nsNf59oSWrptuhQG2cqo6QU0mtVWmKrtVn93ht0vSMIEe+kKJKOMLUuHCLVHqpuXe+Y49vEFNiRpBoo/paFQQI2j6KOAla/6dzA0djKXrk7YqQW5uv35RkDF/5/zMgJpqq6xeBY+9gReGg551LrFvcS+YpqghpzvtBhOcsX/yORO7nvs4btUdSYGFKLxHUEj6o5PgtF4VYVo6a8XEm8t5ilHhgqFflK1IADFSyf/I/mD7cRhPOphBuAxj8OW26Sc2PLrWviRv8nWSckWhZp3LoUMy4g2RVfzP/GCyowvojJhXDJMbn+Oh7x2mPeO+N1zbeM1DBQE9BJ3MDTRbrvFXbIRkuGX/B4yG6MPDSh2iTpRpppWQZXepI=
